/**
 * Constantes de dominio de Steffen ERP
 * Fuente: BUSINESS_RULES.md y DATA_MODEL.md
 */

export const VAT_RATE_PCT = 21.0;
export const VAT_MULTIPLIER = 1.21;
export const PRODUCT_EXTRA_VARIABLE_PCT = 2.0;

export const CODE_PREFIXES = {
  RAW_MATERIAL: 'MPR',
  COMPONENT: 'COM',
  BASE_PRODUCT: 'PBA',
  PRODUCT: 'PRO',
  BULK_LOT: 'GRA',
  PACKAGING: 'ENV',
  ORDER: 'PED',
  PURCHASE: 'CMP',
  REMITTANCE: 'RTO',
  MARGIN_REMITTANCE: 'RTM',
  PATRIMONIAL_MOVEMENT: 'MOV',
  STOCK_MOVEMENT: 'MST',
  FACTORY_MOVEMENT: 'MFA',
  CUSTOMER: 'CLI',
  SUPPLIER: 'PRV',
} as const;

export const SYSTEM_PRICE_LIST_ROLES = {
  SALON: 'SALON_DEFAULT',
  PUBLIC: 'PUBLIC_DEFAULT',
  ECOMMERCE: 'ECOMMERCE_DEFAULT',
} as const;

export const SYSTEM_ACCOUNT_TYPES = {
  CASH_STEFFEN: 'CASH_STEFFEN',
  CASH_MERCADO_LIBRE: 'CASH_MERCADO_LIBRE',
  CUSTOMER_RECEIVABLE: 'CUSTOMER_RECEIVABLE',
  SUPPLIER_PAYABLE: 'SUPPLIER_PAYABLE',
} as const;
